"""The PR body the kernel writes for an autonomous build.

The security guard (`scripts/factory_security.py`) refuses any manifest change whose PR body lacks
a heading titled exactly `## Dependency justification` naming each added or version-changed
package. Model workers never write the PR body; the kernel does, from the compiled contract. A
contract that declares `dependencies` therefore produces the section the guard parses, in the
guard's own terms, and a contract that declares none produces no heading at all.
"""
from __future__ import annotations

from typing import Mapping

DEPENDENCY_HEADING = "## Dependency justification"


def render_dependency_justification(contract: Mapping[str, object]) -> str:
    deps = contract.get("dependencies") or []
    if not isinstance(deps, list) or not deps:
        return ""
    lines = [DEPENDENCY_HEADING, ""]
    for dep in deps:
        if not isinstance(dep, Mapping):
            raise ValueError("contract dependency must be an object")
        name = str(dep.get("name") or "").strip()
        if not name:
            raise ValueError("contract dependency has no name")
        lines.append(f"- `{name}` ({dep.get('ecosystem')}): {str(dep.get('purpose') or '').strip()}")
        lines.append(
            "  - Why existing dependencies are insufficient: "
            + str(dep.get("why_existing_insufficient") or "").strip()
        )
        lines.append("  - Maintenance evidence: " + str(dep.get("maintenance_evidence") or "").strip())
    lines.append("")
    return "\n".join(lines)


def render_pr_body(issue_number: int, attempt: int, contract: Mapping[str, object]) -> str:
    body = (
        f"Fixes #{issue_number}\n\n"
        f"<!-- dark-factory-attempt:{attempt} -->\n\n"
        "Generated by the repo-owned Dark Factory kernel. Model workers are not merge "
        "authorities; deterministic and independent validation follows.\n"
    )
    section = render_dependency_justification(contract)
    if section:
        body += "\n" + section
    return body
